# Generated by Django 4.2.1 on 2023-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="instamojo_id",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
